import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {adjustCustomerLoyalty,fetchCustomerLoyalty,saveLoyaltyProgram} from "../../src/services/loyaltyApi.js";

const response=(status,payload={})=>({ok:status>=200&&status<300,status,json:async()=>payload});

test("customer loyalty derives identity from authenticated cookie",async()=>{let request;await fetchCustomerLoyalty({apiBaseUrl:"https://api.example",fetchImpl:async(...args)=>{request=args;return response(200,{programs:[]})}});assert.equal(request[0],"https://api.example/api/v1/customer/loyalty");assert.equal(request[1].credentials,"include");assert.equal(request[1].method,"GET")});

test("Owner program and adjustment mutations carry CSRF and explicit audit reason",async()=>{const requests=[];const fetchImpl=async(...args)=>{requests.push(args);return response(args[1].method==="POST"?201:200,{})};await saveLoyaltyProgram({name:"Coffee & Tea Loyalty"},"csrf",{fetchImpl});await adjustCustomerLoyalty({customer_user_id:"customer",program_id:"program",quantity:-1,reason:"Correction"},"csrf",{fetchImpl});assert.equal(requests[0][1].headers["X-CSRF-Token"],"csrf");assert.deepEqual(JSON.parse(requests[1][1].body),{customer_user_id:"customer",program_id:"program",quantity:-1,reason:"Correction"})});

test("Home and Account render authenticated real state, errors, and signed-out invitation",()=>{const home=readFileSync(new URL("../../src/pages/HomePage.jsx",import.meta.url),"utf8");const card=readFileSync(new URL("../../src/components/LoyaltyCard.jsx",import.meta.url),"utf8");const account=readFileSync(new URL("../../src/pages/AccountPage.jsx",import.meta.url),"utf8");assert.match(home,/fetchCustomerLoyalty/);assert.match(card,/Sign in to collect loyalty stamps/);assert.match(card,/Free drink ready/);assert.match(card,/Your saved progress is not affected/);assert.match(account,/AccountLoyalty/)});

test("Owner Loyalty includes searchable real products, status, and audited adjustment",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/Search loyalty products/);assert.match(page,/Earns a stamp/);assert.match(page,/Can be a free reward/);assert.match(page,/Program status/);assert.match(page,/Required reason/);assert.match(page,/Save loyalty program/)});

test("Owner Loyalty product controls are associated, touch-oriented, and responsive",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/htmlFor={earningId}/);assert.match(page,/id={earningId}/);assert.match(page,/htmlFor={rewardId}/);assert.match(page,/id={rewardId}/);assert.match(page,/loyalty-eligibility-controls/);assert.match(styles,/\.loyalty-program-form \.loyalty-eligibility-control[^}]*align-items: center;[^}]*box-sizing: border-box;[^}]*min-height: 48px/);assert.match(styles,/:has\(input:checked\)/);assert.match(styles,/@media \(max-width: 480px\)[^{]*{[^}]*\.loyalty-eligibility-controls/s)});

test("Owner Loyalty filtering preserves the unsaved eligibility draft",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/const filtered=useMemo\(\(\)=>\(data\?\.products\|\|\[\]\)\.filter/);assert.match(page,/function toggle\(id,field\)\{setForm/);assert.match(page,/checked={form\.earning_product_ids\.includes\(product\.id\)}/);assert.match(page,/checked={form\.reward_product_ids\.includes\(product\.id\)}/)});

test("Owner Loyalty filtered product list expands with the page without internal overflow",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="loyalty-product-list">{filtered\.map/);assert.match(styles,/\.loyalty-product-list \{[^}]*max-height: none;[^}]*overflow: visible;[^}]*width: 100%;/);assert.doesNotMatch(styles,/\.loyalty-product-list \{[^}]*(?:overflow: auto|max-height: 520px)/);assert.match(styles,/\.loyalty-product-list article \{[^}]*min-width: 0/);assert.match(styles,/\.loyalty-eligibility-controls \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)[^}]*min-width: 0/)});

test("Owner Loyalty filters are a matched accessible pair that stack on narrow screens",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="product-search loyalty-search-control"><Search aria-hidden="true" size=\{18\}\/><input aria-label="Search loyalty products"/);assert.match(page,/className="loyalty-category-filter"/);assert.match(page,/aria-label="Filter loyalty products by category"/);assert.match(styles,/\.loyalty-product-filters \{[^}]*align-items: stretch;[^}]*gap: 12px;[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(220px, \.4fr\)/);assert.match(styles,/\.loyalty-program-form \.loyalty-product-filters label \{[^}]*align-items: center;[^}]*display: flex;[^}]*height: 50px;[^}]*padding: 0 14px/);assert.match(styles,/\.loyalty-search-control svg \{[^}]*flex: 0 0 auto/);assert.match(styles,/\.loyalty-program-form \.loyalty-product-filters input, \.loyalty-program-form \.loyalty-product-filters select \{[^}]*height: 48px;[^}]*min-height: 48px;[^}]*padding: 0/);assert.match(styles,/@media \(max-width: 680px\)[^{]*{[\s\S]*?\.loyalty-product-filters \{ grid-template-columns: 1fr; \}/)});

test("Owner Loyalty UI refinement leaves eligibility arrays and save submission intact",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/earning_product_ids:p\.earning_product_ids\|\|\[\]/);assert.match(page,/reward_product_ids:p\.reward_product_ids\|\|\[\]/);assert.match(page,/saveLoyaltyProgram\(form,session\.csrf_token\)/);assert.match(page,/function toggle\(id,field\)\{setForm\(v=>\(\{\.\.\.v,\[field\]:v\[field\]\.includes\(id\)\?v\[field\]\.filter\(x=>x!==id\):\[\.\.\.v\[field\],id\]\}\)\)\}/)});

test("Owner Loyalty uses a wide bounded desktop workspace without changing global Operations width",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="page-section loyalty-admin-page"/);assert.match(styles,/\.loyalty-admin-page \{[^}]*width: min\(100%, 1080px\)/);assert.match(styles,/\.loyalty-admin-page \.operations-panel \{[^}]*max-width: none;[^}]*width: 100%/);assert.doesNotMatch(styles,/\.operations-panel \{[^}]*width: min\(1080px/)});

test("Owner Loyalty program and product rows use responsive desktop grids",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="operations-panel loyalty-program-settings"/);assert.match(page,/className="form-grid loyalty-program-basics"/);assert.match(page,/className="form-grid loyalty-program-reward"/);assert.match(styles,/\.loyalty-program-basics, \.loyalty-program-reward \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(280px, \.55fr\);[^}]*gap: 16px/);assert.match(styles,/\.loyalty-program-settings input, \.loyalty-program-settings select \{[^}]*min-height: 46px/);assert.match(styles,/\.loyalty-product-list article \{[^}]*grid-template-columns: minmax\(250px, 1fr\) minmax\(430px, 1\.05fr\)[^}]*padding: 10px 14px/);assert.match(styles,/\.loyalty-eligibility-controls \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);assert.match(styles,/@media \(max-width: 820px\)[^{]*\{[\s\S]*?\.loyalty-program-basics, \.loyalty-program-reward \{ grid-template-columns: 1fr; \}[\s\S]*?\.loyalty-product-list article \{ align-items: start; grid-template-columns: 1fr; \}/)});

test("Owner Loyalty desktop layout preserves overflow safety, matched filters, and mobile controls",()=>{const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(styles,/\.loyalty-product-list \{[^}]*max-height: none;[^}]*overflow: visible;[^}]*width: 100%/);assert.match(styles,/\.loyalty-product-filters \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(220px, \.4fr\)/);assert.match(styles,/\.loyalty-program-form \.loyalty-product-filters input, \.loyalty-program-form \.loyalty-product-filters select \{[^}]*min-height: 48px/);assert.match(styles,/@media \(max-width: 680px\)[^{]*\{[\s\S]*?\.loyalty-product-filters \{ grid-template-columns: 1fr; \}/);assert.match(styles,/@media \(max-width: 480px\)[^{]*\{[^}]*\.loyalty-eligibility-controls \{ grid-template-columns: 1fr; \}/);assert.doesNotMatch(styles,/\.loyalty-product-list \{[^}]*(?:overflow-x|overflow-y|overflow: auto)/)});

test("Owner Loyalty save action and Customer Adjustment share the aligned workspace",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="primary-button loyalty-save-button"[^>]*type="submit"/);assert.match(styles,/\.loyalty-save-button \{[^}]*justify-self: start;[^}]*margin: 2px 0 4px/);assert.match(styles,/\.loyalty-admin-page \.loyalty-adjustment \{[^}]*max-width: none;[^}]*width: 100%/)});
